path_data:
  root_dir: 'C:\Users\jniki\Desktop\itub'
  output_dir: 'C:\Users\jniki\Desktop\itub_result'

collect_data:
  file_type: "bom_type1"
  include_file: [ "xls" ]
  exclude_file: []
  include_dir: []
  exclude_dir: [ "_archive" ]
  sheet_names: [ "Summary", "BOM", "Error", "Warning", "Status" ]
  sheet_name_to_concat: "BOM"
  header_row: 4
  engine: "xlrd"