path_data:
  root_dir: 'C:\Users\user\Vilesco\DATA_CORE - Документы\Z34\Z34 CDA STG TUY MFZ 1\RAW\EDMS'
  output_dir: 'C:\Users\user\Desktop\new code'

collect_data:
  file_type: "bom_type1"
  include_file: [ "xls" ]
  exclude_file: ["(2)","(3)","SUPPORT"]
  include_dir: []
  exclude_dir: [ "_archive" ]
  sheet_names: [ "Summary", "BOM", "Error", "Warning", "Status" ]
  sheet_name_to_concat: "BOM"
  header_row: 4
  engine: "xlrd"