path_data:
  root_dir: 'C:\Users\user\Vilesco\DATA_CORE - Документы\V35\V35 CDA STG TUY MFZ 4-5\EDMS_RAW_N34'
  output_dir: 'C:\Users\user\Vilesco\DATA_CORE - Документы\V35\V35 CDA STG TUY MFZ 4-5\EDMS_RAW_N34_AGREGATED'

collect_data:
  file_type: "bom_type1"
  include_file: [ "xls" ]
  exclude_file: ["(2)","(3)","SUPPORT"]
  include_dir: []
  exclude_dir: [ "_archive" ]
  sheet_names: [ "Summary", "BOM", "Error"]
  sheet_name_to_concat: "BOM"
  header_row: 4
  engine: "xlrd"