path_data:
  root_dir: 'D:\Vilesco\Saint Nazaire - Файлы Saint Nazaire\Projects\Z34\CDA\2.HVAC - DUCT ( STM )\4.Drawings, BOM\4.2.ACR\451H'
  output_dir: 'C:\Users\jniki\Desktop'

collect_data:
  file_type: "pdg_type1"
  include_file: [ "xls" ]
  exclude_file: [ "FAB"]
  include_dir: [ "4.2"]
  exclude_dir: [ "_archive" ]
  sheet_names: [ "Data", "Page de Garde" ]
  sheet_name_to_concat: "Data"
  header_row: 1
  engine: "xlrd"