path_data:
  root_dir: 'C:\Users\user\Vilesco\DATA_CORE - Документы\Z34\Z34 CDA HVAC MFZ 1-2\_DUCTING\EDMS_RAW'
  output_dir: 'C:\Users\user\Vilesco\DATA_CORE - Документы\Z34\Z34 CDA HVAC MFZ 1-2\_DUCTING\EDMS_AGREGATED'

collect_data:
  file_type: "pdg_type1"
  include_file: [ "xls" ]
  exclude_file: [ "FAB"]
  include_dir: [ ]
  exclude_dir: [ "_archive" ]
  sheet_names: [ "Data", "Page de Garde" ]
  sheet_name_to_concat: "Data"
  header_row: 1
  engine: "xlrd"