path_data:
  root_dir: 'C:\Users\jniki\Desktop\source'
  output_dir: 'C:\Users\jniki\Desktop\result'

name_list:
  project_db: "project.db"

contract_data:
  ship: []
  mfz: []
  stage_bom: []
  system: []

xls:
  file_type: "xls from edms"
  include_ext: [".xls"]
  exclude_ext: []
  include_file: [ "BOM","RPT" ]
  exclude_file: []
  include_dir: []
  exclude_dir: [ "_archive", "Y34 Released" ]
  sheet_names: [ "Summary", "BOM" ]  # , "Error", "Warning", "Status"
  sheet_name_to_concat: "BOM"
  header_row: 4
  engine: "xlrd"

pdf:
  file_type: "pdf"
  include_file: [ "pdf" ]  # test
  exclude_file: ["STAMPED" ]
  include_dir: [ ]
  exclude_dir: [ "_archive","SPTUNEX" ]

